const KEY='agendapro_demo_v1';
const services=[{id:'s1',name:'Design de sobrancelhas',desc:'Mapeamento, design e finalização.',duration:45,price:75},{id:'s2',name:'Limpeza de pele',desc:'Protocolo completo com avaliação da pele.',duration:60,price:160},{id:'s3',name:'Consulta inicial',desc:'Avaliação e plano de atendimento personalizado.',duration:30,price:90}];
const professionals=[{id:'p1',name:'Marina Costa',role:'Especialista em design',services:['s1','s3']},{id:'p2',name:'Camila Rocha',role:'Esteticista facial',services:['s2','s3']},{id:'p3',name:'Paula Menezes',role:'Atendimento integrado',services:['s1','s2','s3']}];
const seedAppointments=()=>[{id:'a1',serviceId:'s1',professionalId:'p1',date:today(0),time:'09:00',name:'Julia Prado',phone:'(11) 99991-1001',email:'julia@email.com',status:'confirmed'},{id:'a2',serviceId:'s2',professionalId:'p2',date:today(0),time:'10:30',name:'Renata Lima',phone:'(11) 99992-1002',email:'renata@email.com',status:'confirmed'},{id:'a3',serviceId:'s3',professionalId:'p3',date:today(0),time:'13:00',name:'Ana Souza',phone:'(11) 99993-1003',email:'ana@email.com',status:'waiting'}];
function today(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
let appointments=load();let booking={serviceId:null,professionalId:null,date:null,time:null};let step=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)],esc=v=>String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function load(){try{return JSON.parse(sessionStorage.getItem(KEY))||seedAppointments()}catch{return seedAppointments()}}
function save(){sessionStorage.setItem(KEY,JSON.stringify(appointments))}
function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)}
function service(id){return services.find(s=>s.id===id)} function pro(id){return professionals.find(p=>p.id===id)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.i);toast.i=setTimeout(()=>e.classList.remove('show'),2000)}
function renderServices(){const html=services.map((s,i)=>`<article class="service-card"><span class="number">0${i+1}</span><div><h3>${s.name}</h3><p>${s.desc}</p></div><div><div class="service-meta"><span>${s.duration} minutos</span><strong>${money(s.price)}</strong></div><button class="btn secondary" data-service-start="${s.id}">Agendar este serviço</button></div></article>`).join('');$('#serviceGrid').innerHTML=html;$('#bookingServices').innerHTML=services.map(s=>`<button class="choice" data-service="${s.id}"><span><strong>${s.name}</strong><small>${s.duration} min · ${s.desc}</small></span><span class="price">${money(s.price)}</span></button>`).join('');bind()}
function renderProfessionals(){const list=professionals.filter(p=>p.services.includes(booking.serviceId));$('#bookingProfessionals').innerHTML=`<button class="choice" data-professional="auto"><span><strong>Primeiro horário disponível</strong><small>O sistema escolhe o profissional com disponibilidade.</small></span><span class="price">Mais rápido</span></button>`+list.map(p=>`<button class="choice" data-professional="${p.id}"><span><strong>${p.name}</strong><small>${p.role}</small></span><span class="price">Escolher</span></button>`).join('');bind()}
function renderDates(){const dates=[0,1,2,3,4].map(o=>{const d=new Date();d.setDate(d.getDate()+o);return {value:d.toISOString().slice(0,10),weekday:new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(d).replace('.',''),day:d.getDate()}});if(!booking.date)booking.date=dates[0].value;$('#dateStrip').innerHTML=dates.map(d=>`<button class="date-btn ${booking.date===d.value?'active':''}" data-date="${d.value}">${d.weekday}<strong>${String(d.day).padStart(2,'0')}</strong></button>`).join('');renderSlots();bind()}
function possiblePros(){return booking.professionalId==='auto'?professionals.filter(p=>p.services.includes(booking.serviceId)):professionals.filter(p=>p.id===booking.professionalId)}
function renderSlots(){const slots=['08:30','09:00','09:30','10:30','11:00','13:00','14:30','15:00','16:00','17:30','18:00'];const pros=possiblePros();$('#slotGrid').innerHTML=slots.map(time=>{const available=pros.some(p=>!appointments.some(a=>a.date===booking.date&&a.time===time&&a.professionalId===p.id&&a.status!=='cancelled'));return `<button class="slot ${booking.time===time?'selected':''}" data-slot="${time}" ${available?'':'disabled'}>${time}</button>`}).join('');bind()}
function selectAutoProfessional(){if(booking.professionalId!=='auto')return booking.professionalId;const pros=professionals.filter(p=>p.services.includes(booking.serviceId));return pros.find(p=>!appointments.some(a=>a.date===booking.date&&a.time===booking.time&&a.professionalId===p.id&&a.status!=='cancelled'))?.id||pros[0]?.id}
function goStep(n,{scroll=true}={}){step=n;$$('.booking-step').forEach(e=>e.classList.toggle('active',+e.dataset.step===n));$$('.booking-progress i').forEach((e,i)=>e.classList.toggle('active',i<=Math.min(n,3)));updateSummary();if(n===1)renderProfessionals();if(n===2)renderDates();if(scroll)$('#agendar').scrollIntoView({behavior:'smooth',block:'start'})}
function updateSummary(){const s=service(booking.serviceId),p=booking.professionalId&&booking.professionalId!=='auto'?pro(booking.professionalId):null;$('#bookingSummary').innerHTML=`<span>Seu agendamento</span><strong>${s?s.name:'Nenhuma seleção ainda'}</strong><small>${s?`${s.duration} min · ${money(s.price)}${p?' · '+p.name:booking.professionalId==='auto'?' · primeiro disponível':''}${booking.date?' · '+formatDate(booking.date):''}${booking.time?' às '+booking.time:''}`:'Comece escolhendo um serviço.'}</small>`}
function formatDate(v){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(v+'T12:00:00'))}
function bind(){
  $$('[data-service-start]').forEach(b=>b.onclick=()=>{booking={serviceId:b.dataset.serviceStart,professionalId:null,date:null,time:null};goStep(1)});
  $$('[data-service]').forEach(b=>b.onclick=()=>{booking.serviceId=b.dataset.service;goStep(1)});
  $$('[data-professional]').forEach(b=>b.onclick=()=>{booking.professionalId=b.dataset.professional;booking.time=null;goStep(2)});
  $$('[data-date]').forEach(b=>b.onclick=()=>{booking.date=b.dataset.date;booking.time=null;renderDates()});
  $$('[data-slot]').forEach(b=>b.onclick=()=>{booking.time=b.dataset.slot;$$('[data-slot]').forEach(x=>x.classList.toggle('selected',x===b));goStep(3)});
}
$$('.back-step').forEach(b=>b.onclick=()=>goStep(Math.max(0,step-1)));$('#startBooking').onclick=()=>goStep(0);$('#viewAdmin').onclick=$('#adminAccess').onclick=()=>openAdmin();
$('#bookingForm').onsubmit=e=>{e.preventDefault();const professionalId=selectAutoProfessional();const a={id:'a'+Math.random().toString(36).slice(2,8),serviceId:booking.serviceId,professionalId,date:booking.date,time:booking.time,name:$('#bookName').value.trim(),phone:$('#bookPhone').value.trim(),email:$('#bookEmail').value.trim(),status:'confirmed'};appointments.push(a);save();const s=service(a.serviceId),p=pro(a.professionalId);$('#successCopy').textContent=`${a.name}, seu horário foi reservado com sucesso.`;$('#confirmation').innerHTML=`<strong>${s.name}</strong><br>${formatDate(a.date)} às ${a.time}<br>${p.name} · ${s.duration} minutos<br>${money(s.price)}`;goStep(4);renderAdmin();toast('Agendamento criado')};
$('#newBooking').onclick=()=>{booking={serviceId:null,professionalId:null,date:null,time:null};$('#bookingForm').reset();goStep(0)};
function openAdmin(){renderAdmin();const d=$('#adminDialog');if(d.showModal)d.showModal();else d.setAttribute('open','')}
$('#closeAdmin').onclick=()=>$('#adminDialog').close();
$('#resetAgenda').onclick=()=>{appointments=seedAppointments();save();renderAdmin();renderSlots();toast('Agenda demo restaurada')};
function renderAdmin(){const todayA=appointments.filter(a=>a.date===today(0)&&a.status!=='cancelled').sort((a,b)=>a.time.localeCompare(b.time));const revenue=todayA.reduce((s,a)=>s+service(a.serviceId).price,0);$('#adminMetrics').innerHTML=`<article class="admin-metric"><span>Agendamentos hoje</span><strong>${todayA.length}</strong></article><article class="admin-metric"><span>Receita prevista</span><strong>${money(revenue)}</strong></article><article class="admin-metric"><span>Taxa de ocupação</span><strong>${Math.min(100,Math.round(todayA.length/9*100))}%</strong></article>`;$('#adminList').innerHTML=todayA.map(a=>`<article class="admin-appt"><span class="time">${a.time}</span><div><strong>${service(a.serviceId).name}</strong><small>${esc(a.name)} · ${pro(a.professionalId).name}</small></div><select data-status="${a.id}"><option value="confirmed" ${a.status==='confirmed'?'selected':''}>Confirmado</option><option value="waiting" ${a.status==='waiting'?'selected':''}>Aguardando</option><option value="done" ${a.status==='done'?'selected':''}>Concluído</option><option value="cancelled">Cancelado</option></select></article>`).join('')||'<p class="eyebrow">Nenhum agendamento hoje.</p>';const slots=['08:30','09:00','09:30','10:30','11:00','13:00','14:30','15:00','16:00','17:30','18:00'];$('#availabilityGrid').innerHTML=slots.map(t=>`<span class="${todayA.some(a=>a.time===t)?'busy':''}">${t}</span>`).join('');$$('[data-status]').forEach(s=>s.onchange=()=>{const a=appointments.find(a=>a.id===s.dataset.status);a.status=s.value;save();renderAdmin();toast('Status atualizado')})}
renderServices();goStep(0,{scroll:false});